[package]
name = "bbai2c"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Bit-banged async I2C implementation"
readme = "README.md"
repository = "https://github.com/jothan/bbai2c"

[dependencies]
embedded-hal = "1.0"
embedded-hal-async = "1.0"
futures-lite = "2.6"
